# Generated by Django 5.1.1 on 2024-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_tablebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='restauranttable',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tablebooking',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
