# Generated by Django 5.1.1 on 2024-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_tablebooking_table_remove_tablebooking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Modifier',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
