# Generated by Django 5.1.1 on 2024-09-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_order_restaurant_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='updated_by',
        ),
    ]
