# Generated by Django 5.1.1 on 2024-09-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_modified_order_created_at_and_more'),
        ('restaurants', '0005_remove_tablebooking_table_remove_tablebooking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders_from_orders', to='restaurants.restaurant'),
        ),
    ]
