# Generated by Django 5.1.1 on 2024-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_gender_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
