# Generated by Django 5.1.1 on 2024-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_modified_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('employee', 'employee')], default='individual', max_length=32),
        ),
    ]
