# Generated by Django 5.1.1 on 2024-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'employee'), ('deliveryman', 'Deliveryman')], default='individual', max_length=32),
        ),
    ]
